QUESTIONS = [
"Name three of your main qualities, but one of them must be a lie.",
"Which social role comes easiest to you (friend, listener, leader, life of the party, observer)?",
"What about you do people notice first when meeting you?",
"Which of your traits is most often misinterpreted by others?",
"Finish the phrase: 'The main thing in life is...'",
"What do you love that is considered 'strange'?",
"What small detail always gives you away (the way you laugh, a habit of fiddling with something, etc.)?",
"What is your inner age really (not matching your passport one)?",
"If you were an animal, what kind and why?",
"If your life were a movie, what genre would it be and who would direct it?",
"Your life is a book. Which chapter is it now and what is its title?",
"You are a drink. What kind of drink is it (coffee, herbal tea, lemonade, whiskey...)?",
"What color are you and why?",
"What is the weather in your soul right now?",
"Which fictional universe (from film, books, games) is your inner reality most similar to?",
"You are a music genre. Which one?",
"If you had a personal coat of arms, what would be depicted on it?",
"You are a piece of interior. What is it and in which room do you stand?",
"You are on a deserted island. Which three items (not basic for survival) would you take?",
"A wizard grants you one unusual but useless gift for everyday life. What do you choose?",
"You won a ticket for 24 hours to any point in time (past/future). Where and why?",
"What would you do if you saw a stranger crying in the park?",
"Would you have to disgrace yourself nationwide on TV or never eat your favorite food again?",
"Whom would you take with you on a long space journey (a real person or a fictional character)?",
"What is more important to you in a person: sincerity or reliability?",
"You discovered a portal to a parallel world for one day. Would you enter or brick it up?",
"You were offered to forget one painful memory, but along with it an important life lesson would be erased. Do you agree?",
"Your house is on fire. Would you save a photo album, a hard drive with files, or a living plant?",
"Come up with a name for an unknown planet you would like to visit.",
"Describe the perfect sound that calms you.",
"What painting/photograph hangs in your head as an image of happiness?",
"If you created your own calendar, what would the months be called?",
"What mythical creature would you become?",
"Draw your self-portrait in words using emoji style (only emoji, no more than 5).",
"Come up with a ritual (funny or serious) for starting your day.",
"You are opening a museum of one exhibit. What will be in it?",
"Describe the smell of your happiness.",
"What advice would you give yourself at 15?",
"Which childhood belief turned out to be the biggest lie?",
"What did you hate before that you love now?",
"Describe your ideal day in 5 years in three sentences.",
"Which memory would you 'preserve' to relive again and again?",
"What is the most important thing failure taught you?",
"Which part of your past would you gladly get rid of?",
"Which moment became a turning point for you, even if you didn't realize it then?",
"What do you want to manage to do before the end of this year?",
"With what motto would you end your biography?"
]

QUESTIONS_DICT = {i+1: q for i, q in enumerate(QUESTIONS)}
